<a href="https://colab.research.google.com/github/anna-thecs/airlinedelays/blob/main/AirlineDelays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
billboard = pd.read_csv("https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/Billboard%20100s%20Hits%20%20Data/billboard_cleaned.csv")

billboard.head(5)

,song,artist,year,decade,primary_genre,date,weeks_at_number_one,non_consecutive,rating_1,rating_2,...,lyrical_narrative,spoken_word,explicit,foreign_language,written_for_a_play,written_for_a_film,written_for_a_t_v_show,associated_with_dance,topped_the_charts_by_multiple_artist,eurovision_entry
0,Poor Little Fool,Ricky Nelson,1958,1950,Pop,1958-08-04 00:00:00+00:00,2,0,4,5,...,0,0,0,0,0,0,0,0,0,0
1,Nel Blu Dipinto Di Blu,Domenico Modugno,1958,1950,Pop,1958-08-18 00:00:00+00:00,5,1,7,7,...,0,0,0,1,0,0,0,0,0,1
2,Little Star,The Elegants,1958,1950,Rock,1958-08-25 00:00:00+00:00,1,0,5,6,...,0,0,0,0,0,0,0,0,0,0
3,It's All in the Game,Tommy Edwards,1958,1950,Pop,1958-09-29 00:00:00+00:00,6,0,3,3,...,0,0,0,0,0,0,0,0,0,0
4,It's Only Make Believe,Conway Twitty,1958,1950,Pop,1958-11-10 00:00:00+00:00,2,1,7,8,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
billboard.describe()

,year,decade,weeks_at_number_one,non_consecutive,rating_1,rating_2,rating_3,overall_rating,divisiveness,artist_structure,...,lyrical_narrative,spoken_word,explicit,foreign_language,written_for_a_play,written_for_a_film,written_for_a_t_v_show,associated_with_dance,topped_the_charts_by_multiple_artist,eurovision_entry
count,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,...,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000
mean,1987.410365,1982.939677,2.937978,0.085811,5.983857,5.969414,6.438403,6.130558,1.553101,0.781223,...,0.070518,0.089210,0.201359,0.018692,0.002549,0.078165,0.013594,0.019541,0.015293,0.002549
std,18.526153,18.858331,2.643577,0.280204,2.177243,2.008252,2.283813,1.817142,0.963054,0.635818,...,0.256127,0.285168,0.401186,0.135491,0.050443,0.268545,0.115847,0.138476,0.122768,0.050443
min,1958.000000,1950.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1973.000000,1970.000000,1.000000,0.000000,4.000000,5.000000,5.000000,5.000000,0.666667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1986.000000,1980.000000,2.000000,0.000000,6.000000,6.000000,7.000000,6.000000,1.333333,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2002.000000,2000.000000,4.000000,0.000000,8.000000,7.000000,8.000000,7.333333,2.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2025.000000,2020.000000,19.000000,1.000000,10.000000,10.000000,10.000000,10.000000,5.333333,2.500000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
billboard_duplicates = billboard[billboard.duplicated(keep=False)]
billboard_duplicates

Empty DataFrame
Columns: [song, artist, year, decade, primary_genre, date, weeks_at_number_one, non_consecutive, rating_1, rating_2, rating_3, overall_rating, divisiveness, label, parent_label, cdr_genre, discogs_genre, artist_structure, multiple_lead_vocalists, group_named_after_non_lead_singer, posthumous, artist_place_of_origin, front_person_age, artist_male, artist_white, artist_black, songwriters, songwriters_w_o_interpolation_sample_credits, songwriter_male, songwriter_white, artist_is_a_songwriter, artist_is_only_songwriter, producers, producer_male, producer_white, artist_is_a_producer, artist_is_only_producer, songwriter_is_a_producer, time_signature, keys, simplified_key, bpm, energy, danceability, happiness, loudness_d_b, acousticness, vocally_based, bass_based, guitar_based, piano_keyboard_based, orchestral_strings, horns_winds, accordion, banjo, bongos, clarinet, cowbell, falsetto_vocal, flute_piccolo, handclaps_snaps, harmonica, human_whistling, kazoo, mandolin, pedal_lap_steel, ocarina, saxophone, sitar, trumpet, ukulele, violin, song_structure, rap_verse_in_a_non_rap_song, length_sec, instrumental, instrumental_length_sec, intro_length_sec, vocal_introduction, free_time_vocal_introduction, fade_out, live, cover, sample, interpolation, inspired_by_a_different_song, lyrical_topic, lyrical_narrative, spoken_word, explicit, foreign_language, written_for_a_play, written_for_a_film, written_for_a_t_v_show, associated_with_dance, topped_the_charts_by_multiple_artist, eurovision_entry]
Index: []

[0 rows x 97 columns]

In [ ]:
# counts of null values
billboard.isnull().sum()

song                                     0
artist                                   0
year                                     0
decade                                   0
primary_genre                           88
                                        ..
written_for_a_film                       0
written_for_a_t_v_show                   0
associated_with_dance                    0
topped_the_charts_by_multiple_artist     0
eurovision_entry                         0
Length: 97, dtype: int64

In [ ]:
billboard = billboard[["artist", "year", "primary_genre", "date", "weeks_at_number_one", "non_consecutive"]]

# so when you're looking at the nulls, you're only looking at a subset
nulls = billboard[billboard.isnull().any(axis=1)]

# show ALL of the rows
pd.set_option("display.max_rows", None) # max_rows attribute is what makes this work

# show ALL of the columns
pd.set_option("display.max_columns", None)

nulls

,artist,year,primary_genre,date,weeks_at_number_one,non_consecutive
1089,Travis Scott,2019,NaN,2019-10-19 00:00:00+00:00,1,0
1090,Lewis Capaldi,2019,NaN,2019-11-02 00:00:00+00:00,3,1
1091,Selena Gomez,2019,NaN,2019-11-09 00:00:00+00:00,1,0
1092,Post Malone,2019,NaN,2019-11-30 00:00:00+00:00,3,1
1093,The Weeknd,2019,NaN,2019-12-14 00:00:00+00:00,1,0
1094,Mariah Carey,2019,NaN,2019-12-21 00:00:00+00:00,8,1
1095,Roddy Ricch,2020,NaN,2020-01-18 00:00:00+00:00,11,0
1096,The Weeknd,2020,NaN,2020-04-04 00:00:00+00:00,4,1
1097,Drake,2020,NaN,2020-04-18 00:00:00+00:00,1,0
1098,Travis Scott & Kid Cudi,2020,NaN,2020-05-09 00:00:00+00:00,1,0
1099,Doja Cat ft. Nicki Minaj,2020,NaN,2020-05-16 00:00:00+00:00,1,0
1100,Ariana Grande & Justin Bieber,2020,NaN,2020-05-23 00:00:00+00:00,1,0
1101,Megan Thee Stallion ft. Beyoncé,2020,NaN,2020-05-30 00:00:00+00:00,1,0
1102,Lady Gaga & Ariana Grande,2020,NaN,2020-06-06 00:00:00+00:00,1,0
1103,DaBaby ft. Roddy Ricch,2020,NaN,2020-06-13 00:00:00+00:00,7,1
1104,6ix9ine & Nicki Minaj,2020,NaN,2020-06-27 00:00:00+00:00,1,0
1105,Taylor Swift,2020,NaN,2020-08-08 00:00:00+00:00,1,0
1106,Harry Styles,2020,NaN,2020-08-15 00:00:00+00:00,1,0
1107,Cardi B ft. Megan Thee Stallion,2020,NaN,2020-08-22 00:00:00+00:00,4,0
1108,BTS,2020,NaN,2020-09-05 00:00:00+00:00,3,1
1109,Travis Scott ft. Young Thug & M.I.A.,2020,NaN,2020-10-10 00:00:00+00:00,1,0
1110,"Jawsh 685, Jason Derulo, & BTS",2020,NaN,2020-10-17 00:00:00+00:00,1,0
1111,24kGoldn ft. iann dior,2020,NaN,2020-10-24 00:00:00+00:00,8,1
1112,Ariana Grande,2020,NaN,2020-11-07 00:00:00+00:00,1,0
1113,BTS,2020,NaN,2020-12-05 00:00:00+00:00,1,0
1114,Taylor Swift,2020,NaN,2020-12-26 00:00:00+00:00,1,0
1115,Olivia Rodrigo,2021,NaN,2021-01-23 00:00:00+00:00,8,0
1116,Drake,2021,NaN,2021-03-20 00:00:00+00:00,1,0
1117,Cardi B,2021,NaN,2021-03-27 00:00:00+00:00,1,0
1118,Justin Bieber ft. Daniel Caeser & Giveon,2021,NaN,2021-04-03 00:00:00+00:00,1,0
1119,Lil Nas X,2021,NaN,2021-04-10 00:00:00+00:00,1,0
1120,Silk Sonic,2021,NaN,2021-04-17 00:00:00+00:00,2,1
1121,Polo G,2021,NaN,2021-04-24 00:00:00+00:00,2,0
1122,The Weeknd & Ariana Grande,2021,NaN,2021-05-08 00:00:00+00:00,2,0
1123,Olivia Rodrigo,2021,NaN,2021-05-29 00:00:00+00:00,1,0
1124,BTS,2021,NaN,2021-06-05 00:00:00+00:00,10,1
1125,BTS,2021,NaN,2021-07-24 00:00:00+00:00,1,0
1126,The Kid Laroi & Justin Bieber,2021,NaN,2021-08-14 00:00:00+00:00,7,1
1127,Drake ft. Future & Young Thug,2021,NaN,2021-09-18 00:00:00+00:00,1,0
1128,Coldplay & BTS,2021,NaN,2021-10-09 00:00:00+00:00,1,0
1129,Lil Nas X & Jack Harlow,2021,NaN,2021-10-23 00:00:00+00:00,1,0
1130,Adele,2021,NaN,2021-10-30 00:00:00+00:00,10,1
1131,Taylor Swift,2021,NaN,2021-11-27 00:00:00+00:00,1,0
1132,"Carolina Gaitán, Mauro Castillo, Adassa, Rhenz...",2022,NaN,2022-02-05 00:00:00+00:00,5,0
1133,Glass Animals,2022,NaN,2022-03-12 00:00:00+00:00,5,0
1134,Harry Styles,2022,NaN,2022-04-16 00:00:00+00:00,15,1
1135,Jack Harlow,2022,NaN,2022-04-23 00:00:00+00:00,3,1
1136,Future ft. Drake & Tems,2022,NaN,2022-05-14 00:00:00+00:00,1,0
1137,Drake ft. 21 Savage,2022,NaN,2022-07-02 00:00:00+00:00,1,0
1138,Lizzo,2022,NaN,2022-07-30 00:00:00+00:00,2,0
1139,Beyoncé,2022,NaN,2022-08-13 00:00:00+00:00,2,0
1140,Nicki Minaj,2022,NaN,2022-08-27 00:00:00+00:00,1,0
1141,Steve Lacy,2022,NaN,2022-10-08 00:00:00+00:00,3,0
1142,Sam Smith & Kim Petras,2022,NaN,2022-10-29 00:00:00+00:00,1,0
1143,Taylor Swift,2022,NaN,2022-11-05 00:00:00+00:00,8,1
1144,Miley Cyrus,2023,NaN,2023-01-28 00:00:00+00:00,8,1
1145,The Weeknd & Ariana Grande,2023,NaN,2023-03-11 00:00:00+00:00,1,0
1146,Morgan Wallen,2023,NaN,2023-03-18 00:00:00+00:00,16,1
1147,Jimin,2023,NaN,2023-04-08 00:00:00+00:00,1,0
1148,SZA,2023,NaN,2023-04-29 00:00:00+00:00,1,1
1149,Olivia Rodrigo,2023,NaN,2023-07-15 00:00:00+00:00,2,0
1150,Jungkook ft. Latto,2023,NaN,2023-07-29 00:00:00+00:00,1,0
1151,Jason Aldean,2023,NaN,2023-08-05 00:00:00+00:00,1,0
1152,Oliver Anthony Music,2023,NaN,2023-08-26 00:00:00+00:00,2,0
1153,Zach Bryan ft. Kacey Musgraves,2023,NaN,2023-09-09 00:00:00+00:00,1,0
1154,Doja Cat,2023,NaN,2023-09-16 00:00:00+00:00,3,1
1155,Drake ft. SZA,2023,NaN,2023-09-30 00:00:00+00:00,1,0
1156,Drake ft. J Cole,2023,NaN,2023-10-21 00:00:00+00:00,1,0
1157,Taylor Swift,2023,NaN,2023-10-28 00:00:00+00:00,4,1
1158,Taylor Swift,2023,NaN,2023-11-11 00:00:00+00:00,1,0
1159,Jack Harlow,2023,NaN,2023-12-02 00:00:00+00:00,6,1
1160,Brenda Lee,2023,NaN,2023-12-09 00:00:00+00:00,3,1
1161,Ariana Grande,2024,NaN,2024-01-27 00:00:00+00:00,1,0
1162,Megan Thee Stallion,2024,NaN,2024-02-10 00:00:00+00:00,1,0
1163,Beyoncé,2024,NaN,2024-03-02 00:00:00+00:00,2,0
1164,Kanye West & Ty Dolla $ign ft. Rich the Kid & ...,2024,NaN,2024-03-16 00:00:00+00:00,1,0
1165,Ariana Grande,2024,NaN,2024-03-23 00:00:00+00:00,1,0
1166,Teddy Swims,2024,NaN,2024-03-30 00:00:00+00:00,1,0
1167,"Future, Metro Boomin, & Kendrick Lamar",2024,NaN,2024-04-06 00:00:00+00:00,3,0
1168,Hozier,2024,NaN,2024-04-27 00:00:00+00:00,1,0
1169,Taylor Swift ft. Post Malone,2024,NaN,2024-05-04 00:00:00+00:00,2,0
1170,Kendrick Lamar,2024,NaN,2024-05-18 00:00:00+00:00,2,1
1171,Post Malone ft. Morgan Wallen,2024,NaN,2024-05-25 00:00:00+00:00,6,1
1172,Sabrina Carpenter,2024,NaN,2024-06-29 00:00:00+00:00,1,0
1173,Shaboozey,2024,NaN,2024-07-13 00:00:00+00:00,19,1
1174,Morgan Wallen,2024,NaN,2024-11-02 00:00:00+00:00,1,0
1175,Kendrick Lamar,2024,NaN,2024-12-07 00:00:00+00:00,1,0
1176,Bruno Mars & Lady Gaga,2025,NaN,2025-01-11 00:00:00+00:00,2,0